# TASK 1#

In [1]:
import requests
import lxml.html as lh
import pandas as pd

url='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

#Create a handle, page, to handle the contents of the website
page = requests.get(url)

#Store the contents of the website under doc
doc = lh.fromstring(page.content)

#Parse data that are stored between <tr>..</tr> of HTML
tr_elements = doc.xpath('///tr')

#Check the length of the rows
print('Quantity of columns:',[len(T) for T in tr_elements[:1]])

Quantity of columns: [3]

In [2]:
tr_elements = doc.xpath('//tr')
#Create empty list
col=[]
i=0
#For each row, store each first element (header) and an empty list
for t in tr_elements[0]:
    i+=1
    name=t.text_content()
    print (i,name)
    col.append((name,[]))

1 Postal Code

2 Borough

3 Neighborhood

In [3]:
#Since out first row is the header, data is stored on the second row onwards
for j in range(1,len(tr_elements)):
    #T is our j'th row
    T=tr_elements[j]
    
    #If row is not of size 3, the //tr data is not from our table 
    if len(T)!=3:
        break
    
    #i is the index of our column
    i=0
    
    #Iterate through each element of the row
    for t in T.iterchildren():
        data=t.text_content() 
        col[i][1].append(data)
        #Increment i for the next column
        i+=1

In [4]:
print('Number of rows',[len(C) for (title,C) in col])

Number of rows [181, 181, 181]

In [5]:
Dict={title:column for (title,column) in col}
df=pd.DataFrame(Dict)
df.head()

  Postal Code\n           Borough\n               Neighborhood\n
0         M1A\n      Not assigned\n               Not assigned\n
1         M2A\n      Not assigned\n               Not assigned\n
2         M3A\n        North York\n                  Parkwoods\n
3         M4A\n        North York\n           Victoria Village\n
4         M5A\n  Downtown Toronto\n  Regent Park, Harbourfront\n

In [6]:
##Remove N/A Borough rows
df.rename(columns={'Postal Code\n':'Postal Code'}, inplace=True)
df.rename(columns={'Borough\n':'Borough'}, inplace=True)
df.rename(columns={'Neighborhood\n':'Neighborhood'}, inplace=True)
df['Borough'] = df['Borough'].str.replace('\n','')
df['Neighborhood'] = df['Neighborhood'].str.replace('\n','')
df['Postal Code'] = df['Postal Code'].str.replace('\n','')

df.head(12)

   Postal Code           Borough                                 Neighborhood
0          M1A      Not assigned                                 Not assigned
1          M2A      Not assigned                                 Not assigned
2          M3A        North York                                    Parkwoods
3          M4A        North York                             Victoria Village
4          M5A  Downtown Toronto                    Regent Park, Harbourfront
5          M6A        North York             Lawrence Manor, Lawrence Heights
6          M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government
7          M8A      Not assigned                                 Not assigned
8          M9A         Etobicoke      Islington Avenue, Humber Valley Village
9          M1B       Scarborough                               Malvern, Rouge
10         M2B      Not assigned                                 Not assigned
11         M3B        North York                                    Don Mills

In [7]:
import numpy as np

# replace "Not assigned" to NaN
df.replace("Not assigned", np.nan, inplace = True)
df.head(12)

   Postal Code           Borough                                 Neighborhood
0          M1A               NaN                                          NaN
1          M2A               NaN                                          NaN
2          M3A        North York                                    Parkwoods
3          M4A        North York                             Victoria Village
4          M5A  Downtown Toronto                    Regent Park, Harbourfront
5          M6A        North York             Lawrence Manor, Lawrence Heights
6          M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government
7          M8A               NaN                                          NaN
8          M9A         Etobicoke      Islington Avenue, Humber Valley Village
9          M1B       Scarborough                               Malvern, Rouge
10         M2B               NaN                                          NaN
11         M3B        North York                                    Don Mills

In [8]:

missing_data = df.isnull()
missing_data.head(5)

   Postal Code  Borough  Neighborhood
0        False     True          True
1        False     True          True
2        False    False         False
3        False    False         False
4        False    False         False

In [9]:
##ignore Nan Borough
df=df.dropna(subset=['Borough'], axis=0)
df.head(12)

,Postal Code,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
8,M9A,Etobicoke,"Islington Avenue, Humber Valley Village"
9,M1B,Scarborough,"Malvern, Rouge"
11,M3B,North York,Don Mills
12,M4B,East York,"Parkview Hill, Woodbine Gardens"
13,M5B,Downtown Toronto,"Garden District, Ryerson"
14,M6B,North York,Glencairn
17,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov..."

In [10]:
##re indexing
df1=df.reset_index()
df2=df1[['Borough', 'Postal Code', 'Neighborhood']]
df2.head(12)

,Borough,Postal Code,Neighborhood
0,North York,M3A,Parkwoods
1,North York,M4A,Victoria Village
2,Downtown Toronto,M5A,"Regent Park, Harbourfront"
3,North York,M6A,"Lawrence Manor, Lawrence Heights"
4,Downtown Toronto,M7A,"Queen's Park, Ontario Provincial Government"
5,Etobicoke,M9A,"Islington Avenue, Humber Valley Village"
6,Scarborough,M1B,"Malvern, Rouge"
7,North York,M3B,Don Mills
8,East York,M4B,"Parkview Hill, Woodbine Gardens"
9,Downtown Toronto,M5B,"Garden District, Ryerson"
10,North York,M6B,Glencairn
11,Etobicoke,M9B,"West Deane Park, Princess Gardens, Martin Grov..."

In [13]:
print('Borough Data Frame Shape', df2.shape)

Borough Data Frame Shape (104, 3)

# TASK 2##

In [12]:
##get postal code coordinates data
path='https://cocl.us/Geospatial_data'
df3 = pd.read_csv(path)
df3

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
5           M1J  43.744734 -79.239476
6           M1K  43.727929 -79.262029
7           M1L  43.711112 -79.284577
8           M1M  43.716316 -79.239476
9           M1N  43.692657 -79.264848
10          M1P  43.757410 -79.273304
11          M1R  43.750072 -79.295849
12          M1S  43.794200 -79.262029
13          M1T  43.781638 -79.304302
14          M1V  43.815252 -79.284577
15          M1W  43.799525 -79.318389
16          M1X  43.836125 -79.205636
17          M2H  43.803762 -79.363452
18          M2J  43.778517 -79.346556
19          M2K  43.786947 -79.385975
20          M2L  43.757490 -79.374714
21          M2M  43.789053 -79.408493
22          M2N  43.770120 -79.408493
23          M2P  43.752758 -79.400049
24          M2R  43.782736 -79.442259
25          M3A  43.753259 -79.329656
26          M3B  43.745906 -79.352188
27          M3C  43.725900 -79.340923
28          M3H  43.754328 -79.442259
29          M3J  43.767980 -79.487262
..          ...        ...        ...
73          M6C  43.693781 -79.428191
74          M6E  43.689026 -79.453512
75          M6G  43.669542 -79.422564
76          M6H  43.669005 -79.442259
77          M6J  43.647927 -79.419750
78          M6K  43.636847 -79.428191
79          M6L  43.713756 -79.490074
80          M6M  43.691116 -79.476013
81          M6N  43.673185 -79.487262
82          M6P  43.661608 -79.464763
83          M6R  43.648960 -79.456325
84          M6S  43.651571 -79.484450
85          M7A  43.662301 -79.389494
86          M7R  43.636966 -79.615819
87          M7Y  43.662744 -79.321558
88          M8V  43.605647 -79.501321
89          M8W  43.602414 -79.543484
90          M8X  43.653654 -79.506944
91          M8Y  43.636258 -79.498509
92          M8Z  43.628841 -79.520999
93          M9A  43.667856 -79.532242
94          M9B  43.650943 -79.554724
95          M9C  43.643515 -79.577201
96          M9L  43.756303 -79.565963
97          M9M  43.724766 -79.532242
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [17]:
right = df3
left = df2
result = pd.merge(left, right, on=['Postal Code'])
result

,Borough,Postal Code,Neighborhood,Latitude,Longitude
0,North York,M3A,Parkwoods,43.753259,-79.329656
1,North York,M4A,Victoria Village,43.725882,-79.315572
2,Downtown Toronto,M5A,"Regent Park, Harbourfront",43.654260,-79.360636
3,North York,M6A,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,Downtown Toronto,M7A,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494
5,Etobicoke,M9A,"Islington Avenue, Humber Valley Village",43.667856,-79.532242
6,Scarborough,M1B,"Malvern, Rouge",43.806686,-79.194353
7,North York,M3B,Don Mills,43.745906,-79.352188
8,East York,M4B,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937
9,Downtown Toronto,M5B,"Garden District, Ryerson",43.657162,-79.378937
10,North York,M6B,Glencairn,43.709577,-79.445073
11,Etobicoke,M9B,"West Deane Park, Princess Gardens, Martin Grov...",43.650943,-79.554724
12,Scarborough,M1C,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
13,North York,M3C,Don Mills,43.725900,-79.340923
14,East York,M4C,Woodbine Heights,43.695344,-79.318389
15,Downtown Toronto,M5C,St. James Town,43.651494,-79.375418
16,York,M6C,Humewood-Cedarvale,43.693781,-79.428191
17,Etobicoke,M9C,"Eringate, Bloordale Gardens, Old Burnhamthorpe...",43.643515,-79.577201
18,Scarborough,M1E,"Guildwood, Morningside, West Hill",43.763573,-79.188711
19,East Toronto,M4E,The Beaches,43.676357,-79.293031
20,Downtown Toronto,M5E,Berczy Park,43.644771,-79.373306
21,York,M6E,Caledonia-Fairbanks,43.689026,-79.453512
22,Scarborough,M1G,Woburn,43.770992,-79.216917
23,East York,M4G,Leaside,43.709060,-79.363452
24,Downtown Toronto,M5G,Central Bay Street,43.657952,-79.387383
25,Downtown Toronto,M6G,Christie,43.669542,-79.422564
26,Scarborough,M1H,Cedarbrae,43.773136,-79.239476
27,North York,M2H,Hillcrest Village,43.803762,-79.363452
28,North York,M3H,"Bathurst Manor, Wilson Heights, Downsview North",43.754328,-79.442259
29,East York,M4H,Thorncliffe Park,43.705369,-79.349372
...,...,...,...,...,...
73,Central Toronto,M4R,"North Toronto West, Lawrence Park",43.715383,-79.405678
74,Central Toronto,M5R,"The Annex, North Midtown, Yorkville",43.672710,-79.405678
75,West Toronto,M6R,"Parkdale, Roncesvalles",43.648960,-79.456325
76,Mississauga,M7R,Canada Post Gateway Processing Centre,43.636966,-79.615819
77,Etobicoke,M9R,"Kingsview Village, St. Phillips, Martin Grove ...",43.688905,-79.554724
78,Scarborough,M1S,Agincourt,43.794200,-79.262029
79,Central Toronto,M4S,Davisville,43.704324,-79.388790
80,Downtown Toronto,M5S,"University of Toronto, Harbord",43.662696,-79.400049
81,West Toronto,M6S,"Runnymede, Swansea",43.651571,-79.484450
82,Scarborough,M1T,"Clarks Corners, Tam O'Shanter, Sullivan",43.781638,-79.304302
83,Central Toronto,M4T,"Moore Park, Summerhill East",43.689574,-79.383160
84,Downtown Toronto,M5T,"Kensington Market, Chinatown, Grange Park",43.653206,-79.400049
85,Scarborough,M1V,"Milliken, Agincourt North, Steeles East, L'Amo...",43.815252,-79.284577
86,Central Toronto,M4V,"Summerhill West, Rathnelly, South Hill, Forest...",43.686412,-79.400049
87,Downtown Toronto,M5V,"CN Tower, King and Spadina, Railway Lands, Har...",43.628947,-79.394420
88,Etobicoke,M8V,"New Toronto, Mimico South, Humber Bay Shores",43.605647,-79.501321
89,Etobicoke,M9V,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
90,Scarborough,M1W,"Steeles West, L'Amoreaux West",43.799525,-79.318389
91,Downtown Toronto,M4W,Rosedale,43.679563,-79.377529
92,Downtown Toronto,M5W,Stn A PO Boxes,43.646435,-79.374846
93,Etobicoke,M8W,"Alderwood, Long Branch",43.602414,-79.543484
94,Etobicoke,M9W,"Northwest, West Humber - Clairville",43.706748,-79.594054
95,Scarborough,M1X,Upper Rouge,43.836125,-79.205636
96,Downtown Toronto,M4X,"St. James Town, Cabbagetown",43.667967,-79.367675
97,Downtown Toronto,M5X,"First Canadian Place, Underground city",43.648429,-79.382280
98,Etobicoke,M8X,"The Kingsway, Montgomery Road, Old Mill North",43.653654,-79.506944
99,Downtown Toronto,M4Y,Church and Wellesley,43.665860,-79.383160
100,East Toronto,M7Y,"Business reply mail Processing Centre, South C...",43.662744,-79.321558
101,Etobicoke,M8Y,"Old Mill South, King's Mill Park, Sunnylea, Hu...",43.636258,-79.498509
102,Etobicoke,M8Z,"Mimico NW, The Queensway West, South of Bloor,...",43.628841,-79.520999